export const cvData = {
  name: "Mahmoud Ibrahim",
  title: "PhD Researcher in Trustworthy Medical AI",
  eyebrow: "PhD Researcher · Maastricht University & VITO",
  cvPdf: "/cv/Mahmoud-Ibrahim-CV.pdf",
  focus: ["Generative AI", "Agentic systems", "Synthetic data", "Trustworthy & fair AI", "Medical AI", "LLM serving", "AI strategy"],
  proof: [
    { value: "7", label: "publications" },
    { value: "600+", label: "citations" },
    { value: "Keynote", label: "ISC High Performance 2025" },
    { value: "Task lead", label: "synthetic data, Horizon Europe REALM" },
    { value: "Best Poster", label: "DACS PhD Day 2026" },
  ],
  location: "Maastricht, Netherlands / VITO, Belgium",
  email: "mahmoud_ibrahim98@outlook.com",
  phone: "+32-495728562",
  linkedin: "https://www.linkedin.com/in/mahmoud-ibrahim-3135bb1a2/",
  scholar: "https://scholar.google.com/citations?user=mWbnXgUAAAAJ&hl=en",
  github: "https://github.com/mahmoudibrahim98",
  huggingface: "https://huggingface.co/mahmoudibra98",
  image: "/photos/profile.jpg",
  about: [
    "I'm a PhD researcher in AI at Maastricht University and an AI researcher at VITO. For six years I've built generative models (diffusion models, GANs, VAEs and LLM pipelines) that create synthetic medical data, and I use it on both sides of model development: to train models that perform better and more fairly for under-represented patient groups, and to test where a model fails when real data runs out. I lead the synthetic-data work in REALM, a Horizon Europe project with partners across five countries.",
    "I also build what I use. My research runs on a platform I built to plan, dispatch and supervise a fleet of AI agents; my colleagues check my GPU-cluster monitor before they queue a job; my football club runs on an app I built. I serve open models with vLLM on GPU clusters, and I help organisations integrate AI into their workflows where it is needed, building the agents and harnesses that match their needs.",
    "I believe generative AI will change how people and businesses work, and I want to help shape that, especially in the fields where getting it right matters most.",
  ],
  news: [
    {
      date: "Sep 2026",
      type: "Preprint",
      text: "Substantially revised CompDiff preprint on arXiv (v4): zero-shot generation for 16 chest X-ray intersections never seen in training, and a blinded reader study in which two radiologists rated its images the most realistic.",
      link: "#publications",
    },
    {
      date: "Sep 2026",
      type: "Build",
      text: "Built a platform to plan, dispatch and supervise a fleet of AI agents: a GitHub-synced task board, a manager agent, and work that carries on across subscriptions.",
      link: "#project/research-orchestrator",
    },
    {
      date: "Jul 2026",
      type: "Paper",
      text: "Paper accepted at the ECML PKDD SynDAiTE Workshop 2026: Demographically-Conditioned Synthetic Medical Images for Bias Mitigation and Bias Detection in Disease Classifiers. Model weights on Hugging Face.",
      link: "#publications",
    },
    {
      date: "Jun 2026",
      type: "Talk",
      text: "Trainer at the REALM Academy in Brussels, on synthetic data for advanced model evaluation.",
      link: "#events",
    },
    {
      date: "Apr 2026",
      type: "Award",
      text: "Won Best Poster Award at DACS PhD Day 2026 at Maastricht University.",
      link: "#events",
    },
    {
      date: "Apr 2026",
      type: "Talk",
      text: "Served as panelist at the MAIN x Omnium Panel Discussion on AI & the Future of Work in Maastricht.",
      link: "#events",
    },
    {
      date: "Mar 2026",
      type: "Preprint",
      text: "New preprint released: CompDiff, compositional diffusion for fair medical image generation across demographic intersections.",
      link: "#publications",
    },
    {
      date: "2026",
      type: "Conference",
      text: "Attended MENAML 2026 at KAUST, Saudi Arabia.",
      link: "#events",
    },
    {
      date: "Oct 2025",
      type: "Paper",
      text: "Paper accepted at the ECML PKDD SynDAiTE Workshop 2025: Enabling Granular Subgroup Level Model Evaluations by Generating Synthetic Medical Time Series.",
      link: "#publications",
    },
    {
      date: "2025",
      type: "Talk",
      text: "Delivered keynote at ISC High Performance 2025 in Hamburg, Germany.",
      link: "#events",
    },
    {
      date: "2025",
      type: "Paper",
      text: "Published a systematic review on Generative AI for Synthetic Data Across Multiple Medical Modalities in Computers in Biology and Medicine.",
      link: "#publications",
    },
  ],
  education: [
    {
      degree: "PhD in Artificial Intelligence",
      institution: "Maastricht University, The Netherlands",
      period: "Apr 2023 - Current",
      description: "Trustworthy generative AI for medicine: fair synthetic data for under-represented and intersectional patient subgroups, fine-grained performance evaluation, and automated performance monitoring of medical AI. Supervised by Prof. Dr. Michel Dumontier.",
      logo: "/photos/maastricht-logo.png",
    },
    {
      degree: "Advanced Master's in Artificial Intelligence",
      institution: "KU Leuven, Belgium",
      period: "Sep 2021 - Sep 2022",
      description: "Graduated Magna Cum Laude. Focus Area: Big Data Analytics (Hadoop), Computer Vision, Uncertainty Quantification. Thesis supervised by Prof. Dr. Matthew B. Blaschko.",
      logo: "/photos/ku-leuven-logo.png",
    },
    {
      degree: "Bachelor of Engineering in Electrical and Computer Engineering",
      institution: "American University of Beirut, Lebanon",
      period: "Sep 2016 - May 2020",
      description: "Graduated with Distinction | Dean's Honor List. Minor in Mathematics.",
      logo: "/photos/aub-logo.png",
    },
    {
      degree: "Exchange Program - Master of Science in Mechatronics Engineering",
      institution: "Politecnico Di Torino, Italy",
      period: "Feb 2019 - Jul 2019",
      description: "Relevant Coursework: Estimation, Filtering and System Identification (30/30), Robotics (30/30), Nonlinear Control and Aerospace Application (29/30)",
      logo: "/photos/polito-logo.png",
    },
  ],
  experience: [
    {
      role: "AI Consultant",
      company: "Freelance",
      period: "Jan 2025 - Present",
      tasks: [
        "Help organisations integrate AI into their workflows where it is needed: analyse how their teams work today and identify where generative AI and agents add real value.",
        "Design and build agents and agent harnesses that match each organisation's needs.",
        "Translate technical trade-offs (reliability, data access, cost, risk) into clear recommendations for non-technical decision-makers.",
      ],
      skills: ["AI Integration", "AI Agents", "Agent Harnesses", "LLMs"],
    },
    {
      role: "AI Researcher",
      company: "VITO, Belgium",
      period: "Oct 2022 - Present",
      tasks: [
        "Synthetic-data task leader in REALM, a Horizon Europe project building a framework for regulators, developers and clinicians to evaluate medical AI software; coordinating with partners in Greece, the Netherlands, Belgium, Poland and Croatia.",
        "Develop generative models (diffusion models, GANs, VAEs, LLM-based pipelines) for structured, time-series and imaging medical data.",
        "Investigate subgroup performance gaps and bias amplification in models trained or tested on synthetic data.",
        "Built a SLURM GPU-cluster monitor now being adopted across VITO; among the cluster's most active users.",
        "Trainer at the REALM Academy (Brussels, 2026) on synthetic data for advanced model evaluation.",
      ],
      skills: ["Python", "PyTorch", "Diffusion Models", "GANs", "LLMs", "SLURM", "vLLM"],
    },
    {
      role: "Deep Learning Researcher Intern (Master's thesis)",
      company: "VITO, Belgium",
      period: "Oct 2021 - June 2022",
      tasks: [
        "Thesis \"Uncertainty Quantification in DR Screening: A Cost-effective Approach\" (graded 18/20): implemented and compared uncertainty quantification methods, MC Dropout and ensembles, for deep learning models detecting diabetic retinopathy on fundus images.",
      ],
      skills: ["Python", "TensorFlow", "Keras"],
    },
    {
      role: "Machine Learning Research Assistant",
      company: "United Arab Emirates University (UAEU), UAE",
      period: "Aug 2020 - Sep 2021",
      tasks: [
        "Wrote all the code and ran all the experiments behind three papers on synthetic data generation and evaluation, now cited about 400 times.",
        "Built a web portal for dynamic participant consent in research studies.",
      ],
      skills: ["Python", "R", "SQL", "PHP", "JavaScript"],
    },
  ],
  publications: [
    {
      title: "CompDiff enables fair and zero-shot medical image generation across demographic intersections through compositional diffusion",
      authors: "M. Ibrahim, B. Elen, C. Sun, A. Jiblawi, M. M. Saleh, Maryam K. Ibrahim, G. Ertaylan, M. Dumontier",
      journal: "arXiv preprint (under review)",
      year: "2026",
      link: "https://arxiv.org/abs/2603.16551",
      site: "https://mahmoudibrahim98.github.io/compdiff-site/",
      extra: [
        { label: "Code", url: "https://github.com/mahmoudibrahim98/CompDiff" },
        { label: "X-ray weights", url: "https://huggingface.co/mahmoudibra98/compdiff-chest-xray" },
        { label: "Fundus weights", url: "https://huggingface.co/mahmoudibra98/compdiff-fundus" },
      ],
    },
    {
      title: "Demographically-Conditioned Synthetic Medical Images for Bias Mitigation and Bias Detection in Disease Classifiers",
      authors: "M. Ibrahim, B. Elen, C. Sun, G. Ertaylan, M. Dumontier",
      journal: "ECML PKDD SynDAiTE Workshop 2026",
      year: "2026",
      link: "https://arxiv.org/abs/2607.14984",
      extra: [{ label: "Weights", url: "https://huggingface.co/mahmoudibra98/covid-ct-sd21" }],
    },
    {
      title: "Enabling Granular Subgroup Level Model Evaluations by Generating Synthetic Medical Time Series",
      authors: "M. Ibrahim, B. Elen, C. Sun, G. Ertaylan, M. Dumontier",
      journal: "ECML PKDD SynDAiTE Workshop 2025",
      year: "2025",
      link: "https://arxiv.org/abs/2510.19728",
      site: "https://mahmoudibrahim98.github.io/icu-auto-diff-site/",
    },
    {
      title: "Generative AI for Synthetic Data Across Multiple Medical Modalities: A Systematic Review of Recent Developments and Challenges",
      authors: "M. Ibrahim et al.",
      journal: "Computers in Biology and Medicine, vol. 189",
      year: "2025",
      doi: "10.1016/j.compbiomed.2025.109834",
    },
    {
      title: "A New PCA-based Utility Measure for Synthetic Data Evaluation",
      authors: "F. Dankar, M. Ibrahim",
      journal: "Arxiv",
      year: "2022",
      link: "https://arxiv.org/abs/2212.05595",
    },
    {
      title: "A Multi-Dimensional Evaluation of Synthetic Data Generators",
      authors: "F. Dankar, M. Ibrahim, L. Ismail",
      journal: "IEEE Xplore, vol. 10",
      year: "2022",
      doi: "10.1109/ACCESS.2022.3144765",
    },
    {
      title: "Fake It Till You Make It: Guidelines for Effective Synthetic Data Generation",
      authors: "F. Dankar, M. Ibrahim",
      journal: "Applied Sciences, vol. 11",
      year: "2021",
      doi: "10.3390/app11052158",
    },
  ],
  skills: {
    languages: ["Arabic (Native)", "English (Professional)", "French (Basic)"],
    technical: ["Python", "PyTorch", "TensorFlow", "Hugging Face", "Diffusion Models", "LLMs", "vLLM", "Ollama", "Unsloth", "SLURM", "TypeScript", "React", "PostgreSQL", "SQL", "R", "Claude Code", "Codex"],
  },
  talks: [
    {
      title: "Synthetic data for advanced model evaluation",
      event: "Trainer at the REALM Academy",
      location: "Brussels, Belgium",
      date: "June 2026",
    },
    {
      title: "AI & the Future of Work",
      event: "Panelist at MAIN x Omnium Panel Discussion",
      location: "Maastricht, Netherlands",
      date: "April 2026",
      images: ["/photos/main-panel-1.jpg", "/photos/main-panel-2.jpg"],
    },
    {
      title: "Generative AI for Synthetic data across multiple medical modalities",
      event: "Keynote at ISC High Performance 2025",
      location: "Hamburg, Germany",
      date: "2025",
      image: "/photos/hamburg.jpg",
    },
  ],
  conferences: [
    {
      name: "DACS PhD Day 2026",
      location: "Maastricht University, The Netherlands",
      date: "2026",
      award: "Best Poster Award",
      details: "Poster presented",
      image: "/photos/dacs.png",
    },
    {
      name: "MENAML 2026",
      location: "KAUST, Saudi Arabia",
      date: "2026",
      details: "Attended",
      image: "/photos/menaml2026.jpg",
    },
    {
      name: "MENAML 2025",
      location: "Qatar",
      date: "2025",
      details: "Poster accepted and presented",
      image: "/photos/menaml2025.jpg",
    },
    {
      name: "ECML PKDD 2026",
      location: "Naples, Italy",
      date: "2026",
      details: "Paper accepted at the SynDAiTE workshop",
    },
    {
      name: "ECML PKDD 2025",
      location: "Porto, Portugal",
      date: "2025",
      details: "Paper accepted and presented at SynDAiTE workshop",
      link: "https://aiimlab.org/events/ECML_PKDD_2025_SynDAiTE_Synthetic_Data_for_AI_Trustworthiness_and_Evolution",
    },
    {
      name: "ECML PKDD 2023",
      location: "Turin, Italy",
      date: "2023",
      details: "Poster presented at PhD Forum",
    },
  ],
  workshops: [
    {
      name: "Life Sciences Industry Workshop",
      role: "Organizer",
      date: "May 2023",
      link: "https://www.lifesciencesatwork.nl/events/2023/05/life-sciences-industry",
    }
  ],
};
